name: peek_example
description: A minimal app showing Peek's user interface with demo data.
publish_to: none
version: 1.0.0
resolution: workspace

environment:
  sdk: ^3.7.0
  flutter: '>=3.29.0'

dependencies:
  dio: ^5.7.0
  flutter:
    sdk: flutter
  peek: ^0.1.0
  peek_dio: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
