version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly

  - package-ecosystem: pub
    directories:
      - /
      - /packages/*
      - /packages/peek/example
    schedule:
      interval: weekly
